[unix_http_server]
file=/tmp/supervisor.sock   ; path to your socket file

[supervisord]
logfile=/var/log/supervisord.log ; supervisord log file
logfile_maxbytes=50MB                        ; maximum size of logfile before rotation
logfile_backups=10                           ; number of backed up logfiles
loglevel=info                                ; info, debug, warn, trace
pidfile=/var/run/supervisord.pid             ; pidfile location
nodaemon=false                               ; run supervisord as a daemon (default false)
minfds=1024                                  ; number of startup file descriptors (default 1024)
minprocs=200                                 ; number of process descriptors (default 200)
;umask=022                                   ; umask for supervisord process (default 022)
;user=chrism                                 ; default user (default current user)
;directory=/tmp                              ; directory in which supervisord will start subprocesses (default cwd)
childlogdir=/var/log/            ; where child log files will live

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock ; use a unix:// URL for a unix socket

[program:hermes-gateway]
command=/opt/hermes-agent/venv/bin/python -m hermes_cli.main gateway run --replace
directory=/root/.hermes/
user=root

environment=
    PATH="/opt/hermes-agent/venv/bin:/opt/hermes-agent/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
    VIRTUAL_ENV="/opt/hermes-agent/venv"

autostart=true
autorestart=unexpected
startsecs=10
exitcodes=0

stopsignal=TERM
stopwaitsecs=15
stopasgroup=true
killasgroup=true

stdout_logfile=/root/.hermes/logs/hermes-gateway.out.log
stderr_logfile=/root/.hermes/logs/hermes-gateway.err.log